version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: goplayertui
    main: ./cmd/goplayertui
    binary: goplayertui
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - assets/*
      - LICENSE
      - README.md
nfpms:
  - id: goplayertui-packages
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    vendor: ader999
    homepage: https://github.com/ader999/GoPlayerTUI
    maintainer: ader999
    description: Reproductor de música TUI escrito en Go
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    contents:
      - src: ./assets/goplayertui.desktop
        dst: /usr/share/applications/goplayertui.desktop
      - src: ./assets/goplayertui.png
        dst: /usr/share/pixmaps/goplayertui.png
aurs:
  - name: goplayertui-bin
    homepage: https://github.com/ader999/GoPlayerTUI
    description: Reproductor de música TUI escrito en Go
    maintainers:
      - overader <goplayertui@codeader.com>
    license: MIT
    private_key: /tmp/aur_key
    git_url: ssh://aur@aur.archlinux.org/goplayertui-bin.git
    package: |-
      # bin
      install -Dm755 "./goplayertui" "${pkgdir}/usr/bin/goplayertui"
      
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/goplayertui/LICENSE"

      # desktop file
      install -Dm644 "./assets/goplayertui.desktop" "${pkgdir}/usr/share/applications/goplayertui.desktop"

      # icon
      install -Dm644 "./assets/goplayertui.png" "${pkgdir}/usr/share/pixmaps/goplayertui.png"
    commit_author:
      name: overader
      email: goplayertui@codeader.com
    commit_msg_template: "AUR package update: {{ .ProjectName }} version {{ .Tag }}"
