version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: goplayertui
    main: ./cmd/goplayertui
    binary: goplayertui
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: goplayertui-packages
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    vendor: ader999
    homepage: https://github.com/ader999/GoPlayerTUI
    maintainer: ader999
    description: Reproductor de música TUI escrito en Go
    license: MIT
    formats:
      - deb
      - rpm
      - apk
